#!/bin/bash
set -eu

if [ "$#" -ne 1 ]; then
    echo "Expected exactly one argument, a github package reference"
fi

ORDERLY_CONTAINERS=$(docker ps --format '{{.Names}}' | grep "^orderly-web-orderly")
REF=$1

for CONTAINER in $ORDERLY_CONTAINERS; do
    echo "Installing $REF into $CONTAINER"
    docker exec -it $CONTAINER Rscript -e "remotes::install_github(\"$REF\", upgrade = FALSE)"
done
