#!/bin/sh
set -ex

# NOTE: In order to do a clone while retaining .Renviron some
# slight of hand is required, and a simple clone won't actually work
# (clone only works into an empty directory).
git init /orderly
git -C /orderly remote add origin git@github.com:vimc/montagu-reports.git
git -C /orderly pull origin master
git -C /orderly branch -u origin/master

# We might as well build a blank index
/usr/bin/montagu-reports-init
