#!/usr/bin/env Rscript
local({
  ## This will just create a blank db but not do the rebuild, which is
  ## probably more useful
  path <- "/orderly"

  ## These are never referenced, so it does not matter that they're
  ## not real.
  Sys.setenv("MONTAGU_PASSWORD" = "changeme",
             "MONTAGU_USER" = "vimc",
             "MONTAGU_HOST" = "localhost",
             "MONTAGU_PORT" = "5432")

  con <- orderly::orderly_db("destination", config = path)
  DBI::dbDisconnect(con)
  message("Initialised orderly repo at ", path)
})
