#!/usr/bin/env Rscript
local({
  args <- commandArgs(TRUE)
  if (length(args) != 1L) {
    stop("Usage: init <path>")
  }
  path <- args[[1L]]
  path_config <- "/etc/montagu/orderly_config.yml"

  ## These are never referenced, so it does not matter that they're
  ## not real.
  Sys.setenv("MONTAGU_PASSWORD" = "changeme",
             "MONTAGU_USER" = "vimc",
             "MONTAGU_HOST" = "localhost",
             "MONTAGU_PORT" = "5432")

  orderly::orderly_init(path, quiet = TRUE)
  if (!file.copy(path_config, path, overwrite = TRUE)) {
    stop("Error copying configuration")
  }
  con <- orderly::orderly_db("destination", config = path)
  DBI::dbDisconnect(con)

  message("Initialised orderly repo at ", path)
})
