#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

# In case we switch agents between steps
[ ! -z $(docker images -q $TAG_SHA) ] || docker pull $TAG_SHA

# Push the human-readable tagged versions here (the SHA versions were
# pushed during build)
docker tag $TAG_SHA $TAG_BRANCH
docker push $TAG_BRANCH

if [ $GIT_BRANCH == "master" ]; then
    ORDERLY_VERSION=$(docker run --rm --entrypoint bash \
                             $TAG_SHA \
                             -c 'echo $ORDERLY_VERSION')
    TAG_VERSION="${PACKAGE_ORG}/${PACKAGE_NAME}:${ORDERLY_VERSION}"
    docker tag $TAG_SHA $TAG_LATEST
    docker tag $TAG_SHA $TAG_VERSION
    docker push $TAG_LATEST
    docker push $TAG_VERSION
fi


# Legacy repository support
PRIVATE_REPOSITORY=docker.montagu.dide.ic.ac.uk:5000
PRIVATE_TAG="${PRIVATE_REPOSITORY}/${PACKAGE_NAME}:${GIT_SHA}"
PRIVATE_BRANCH="${PRIVATE_REPOSITORY}/${PACKAGE_NAME}:${GIT_BRANCH}"
PRIVATE_VERSION="${PRIVATE_REPOSITORY}/${PACKAGE_NAME}:${ORDERLY_VERSION}"
docker tag $TAG_SHA $PRIVATE_TAG
docker tag $TAG_SHA $PRIVATE_BRANCH
docker push $PRIVATE_TAG
docker push $PRIVATE_BRANCH

if [ $GIT_BRANCH == "master" ]; then
    docker tag $TAG_SHA $PRIVATE_VERSION
    docker push $PRIVATE_VERSION
fi
