#!/usr/bin/env bash
set -eu

GIT_ID=$(git rev-parse --short=7 HEAD)
GIT_BRANCH=$(git symbolic-ref --short HEAD)
REGISTRY=docker.montagu.dide.ic.ac.uk:5000
PUBLIC_REGISTRY=vimc
NAME=montagu-orderly

PRIVATE_DOCKER_TAG=$REGISTRY/$NAME
PRIVATE_DOCKER_COMMIT_TAG=$REGISTRY/$NAME:$GIT_ID
PRIVATE_DOCKER_BRANCH_TAG=$REGISTRY/$NAME:$GIT_BRANCH

docker build --pull \
       --build-arg GIT_ID=$GIT_ID \
       --build-arg GIT_BRANCH=$GIT_BRANCH \
       --tag $PRIVATE_DOCKER_COMMIT_TAG \
       --tag $PRIVATE_DOCKER_BRANCH_TAG \
       -f docker/Dockerfile .

docker push $PRIVATE_DOCKER_BRANCH_TAG
docker push $PRIVATE_DOCKER_COMMIT_TAG

if [ $GIT_BRANCH = "master" ]; then
    ORDERLY_VERSION=$(docker run --rm --entrypoint bash \
                             $PRIVATE_DOCKER_COMMIT_TAG \
                             -c 'echo $ORDERLY_VERSION')

    PUBLIC_DOCKER_COMMIT_TAG=$PUBLIC_REGISTRY/$NAME:$GIT_ID
    PUBLIC_DOCKER_BRANCH_TAG=$PUBLIC_REGISTRY/$NAME:$GIT_BRANCH
    PUBLIC_DOCKER_VERSION_TAG=$PUBLIC_REGISTRY/$NAME:v$ORDERLY_VERSION
    PRIVATE_DOCKER_VERSION_TAG=$REGISTRY/$NAME:v$ORDERLY_VERSION

    docker tag $PRIVATE_DOCKER_BRANCH_TAG $PUBLIC_DOCKER_COMMIT_TAG
    docker tag $PRIVATE_DOCKER_BRANCH_TAG $PUBLIC_DOCKER_BRANCH_TAG
    docker tag $PRIVATE_DOCKER_BRANCH_TAG $PUBLIC_DOCKER_VERSION_TAG
    docker tag $PRIVATE_DOCKER_BRANCH_TAG $PRIVATE_DOCKER_VERSION_TAG

    docker push $PUBLIC_DOCKER_COMMIT_TAG
    docker push $PUBLIC_DOCKER_BRANCH_TAG
    docker push $PUBLIC_DOCKER_VERSION_TAG
    docker push $PRIVATE_DOCKER_VERSION_TAG
fi
