#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

# In case we switch agents between steps
[ ! -z $(docker images -q $TAG_SHA) ] || docker pull $TAG_SHA
[ ! -z $(docker images -q $TAG_WORKER_SHA) ] || docker pull $TAG_WORKER_SHA

VOLUME_ID=$(docker volume create)
function cleanup {
    echo "Cleaning up!"
    set +e
    docker volume rm $VOLUME_ID
}
trap cleanup EXIT

docker run --rm --entrypoint /usr/bin/orderly_init \
       -v "$VOLUME_ID":/orderly \
       "$TAG_SHA" \
       "/orderly"

docker run --rm --entrypoint cat \
       -v "$VOLUME_ID":/orderly \
       "$TAG_SHA" \
       "/orderly/orderly_config.yml"

docker run --rm --entrypoint cat \
       -v "$VOLUME_ID":/orderly \
       "$TAG_WORKER_SHA" \
       "/orderly/orderly_config.yml"
